### PR TITLE
[Fix #984] Fixing node response type

### LINKED ISSUE #984: HtppExecutor is not deserializing array nodes responses

### PR DESCRIPTION
**Pull request by fjtirado**
Fix https://github.com/serverlessworkflow/sdk-java/issues/984

### CODE REVIEW

File: impl/http/src/main/java/io/serverlessworkflow/impl/executors/http/HttpExecutor.java [hunk 1]
```diff
@@ -187,16 +187,17 @@ private static RequestSupplier buildRequestSupplier(
...
+          return converter.toModel(
+              application.modelFactory(),
+              node,
+              request.post(converter.toEntity(model), model.objectClass()));
+        };
       case HttpMethod.GET:
       default:
         return (request, w, t, n) ->
-            converter.toModel(application.modelFactory(), n, request.get(n.objectClass()));
+            converter.toModel(application.modelFactory(), n, request.get(Object.class));
```
Comment (fjtirado) [inline impl/http/src/main/java/io/serverlessworkflow/impl/executors/http/HttpExecutor.java]: This should be handled in a more smart way, because although this will work, its doing a lot of Map-JsonNode unneeded conversion. 
Basically converter should be configurable so we can hardcode JsonNode.class there (n.objectClass is not the current response class but the model class, thats the BUG!!!!)
