### PR TITLE
Fix #213 - Make  a required property for Retry and verify RetryDef

### LINKED ISSUE #213: Retry definition validation doesn't work
**Given**:
Workflow definition to be validated

```json
{
  "id": "workflow_1",
  "name": "workflow_1",
  "description": "workflow_1",
  "version": "1.0",
  "specVersion": "0.8",
  "start": "Task1",
  "functions": [
    {
      "name": "increment",
      "type": "custom",
      "operation": "worker"
    }
  ],
  "retries": [
    {
      "maxAttempts": 3
    }
  ],
  "states": [
    {
      "name": "Task1",
      "type": "operation",
      "actionMode": "sequential",
      "actions": [
        {
          "functionRef": {
            "refName": "increment",
            "arguments": {
              "input": "some text"
            }
          },
          "retryRef": "const",
          "actionDataFilter": {
            "toStateData": "${ .result }"
          }
        }
      ],
      "end": true
    }
  ]
}
```

**Expected result:**
Validation failed (because of `name` of `RetryDefinition` missed)

**Actual result:**
Validation passed.

The same result(validation passed) if 'name' field is empty or/and `maxAttempts` not defined.
According to specification 'name ' is required and `maxAttempts` not.
But in the `retrydef.json` schema they are required both.

Could you please support us in this question? May be we miss something?

### PR DESCRIPTION
**Pull request by ricardozanini**
**Many thanks for submitting your Pull Request :heart:!**

**What this PR does / why we need it**:
Fixes #213 

**Special notes for reviewers**:
I've also removed a few deprecated usages (see put/set) and simplified a few methods in the class I was working on.

**Additional information (if needed):**

### CODE REVIEW

File: validation/src/main/java/io/serverlessworkflow/validation/WorkflowValidatorImpl.java [hunk 1]
```diff
@@ -334,32 +359,48 @@ public WorkflowValidator reset() {
...
     if (functions != null) {
-      FunctionDefinition fun =
-          functions.stream().filter(f -> f.getName().equals(functionName)).findFirst().orElse(null);
-
-      return fun == null ? false : true;
+      return functions.stream()
+              .filter(f -> f.getName().equals(functionName))
+              .findFirst()
+              .orElse(null)
+          == null;
```
Comment (fjtirado) [inline validation/src/main/java/io/serverlessworkflow/validation/WorkflowValidatorImpl.java]:
```suggestion
      return !functions.stream().anyMatch(f -> f.getName().equals(functionName));
```

File: validation/src/main/java/io/serverlessworkflow/validation/WorkflowValidatorImpl.java [hunk 2]
```diff
@@ -334,32 +359,48 @@ public WorkflowValidator reset() {
...
     if (eventName == null) {
-      return true;
+      return false;
     }
     if (events != null) {
-      EventDefinition eve =
-          events.stream().filter(e -> e.getName().equals(eventName)).findFirst().orElse(null);
-      return eve == null ? false : true;
+      return events.stream().filter(e -> e.getName().equals(eventName)).findFirst().orElse(null)
+          == null;
```
Comment (fjtirado) [inline validation/src/main/java/io/serverlessworkflow/validation/WorkflowValidatorImpl.java]:
```suggestion
      return !events.stream().anyMatch(e -> e.getName().equals(eventName));
```

File: validation/src/main/java/io/serverlessworkflow/validation/WorkflowValidatorImpl.java [hunk 3]
```diff
@@ -334,32 +359,48 @@ public WorkflowValidator reset() {
...
+  private boolean isMissingRetryDefinition(String retryName, List<RetryDefinition> retries) {
+    if (retries != null) {
+      return retries.stream()
+              .filter(f -> f.getName() != null && f.getName().equals(retryName))
+              .findFirst()
+              .orElse(null)
+          == null;
+    } else {
+      return true;
     }
```
Comment (fjtirado) [inline validation/src/main/java/io/serverlessworkflow/validation/WorkflowValidatorImpl.java]:
```suggestion
    return retries == null || ! retries.stream()
              .anyMatch(f -> f.getName() != null && f.getName().equals(retryName));
```

**Review by fjtirado — COMMENTED** [review]
Some enhacements on stream handling

**Review by fjtirado — APPROVED** [review]
