### PR TITLE
Fix #1189 - Refactor listen/emit tasks to add proper event filtering

### LINKED ISSUE #1189: MIssing Event Correlation to the Java DSL
**What happened**:
We are currently missing the Event Correlation filter on our Java DSL: https://github.com/serverlessworkflow/specification/blob/main/dsl-reference.md#event-filter

**What you expected to happen**:
To use event correlation filters in the DSL

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- Specification version used:

### PR DESCRIPTION
**Pull request by ricardozanini**
**Many thanks for submitting your Pull Request :heart:!**
Closes #1189 

**What this PR does / why we need it**:

**Special notes for reviewers**:

**Additional information (if needed):**

### CODE REVIEW

File: experimental/fluent/func/src/test/java/io/serverlessworkflow/fluent/func/FuncDSLTest.java [hunk 1]
```diff
@@ -185,11 +178,54 @@ void mixed_chaining_order_and_exports() {
...
+  @DisplayName("listen with consumed().correlate() populates EventFilter correlation properties")
+  void listen_with_consumed_and_correlate_populates_event_filter() {
+    Workflow wf =
+        FuncWorkflowBuilder.workflow("listen-correlate")
+            .tasks(
+                listen(
+                    "waitPayment",
+                    to().all(
+                            consumed("org.acme.payment.success")
+                                .correlate("orderId", c -> c.from("${ .orderId }")))))
```
Comment (fjtirado) [inline experimental/fluent/func/src/test/java/io/serverlessworkflow/fluent/func/FuncDSLTest.java]: I hava problem with this syntax,  whats exactly the meaning of this filter?

File: fluent/spec/src/main/java/io/serverlessworkflow/fluent/spec/AbstractListenTaskBuilder.java [hunk 2]
```diff
@@ -70,12 +70,12 @@ public ListenTask build() {
   public static final class CorrelatePropertyBuilder {
     private final CorrelateProperty prop = new CorrelateProperty();
 
-    public ListenTaskBuilder.CorrelatePropertyBuilder from(String expr) {
+    public CorrelatePropertyBuilder from(String expr) {
```
Comment (fjtirado) [inline fluent/spec/src/main/java/io/serverlessworkflow/fluent/spec/AbstractListenTaskBuilder.java:73]: This is not currently supported by the implementation, see [issue](https://github.com/serverlessworkflow/sdk-java/issues/1206)
I think we should avoid adding to the DSL idioms not supported by the implementation.
